### ISSUE TITLE
Failed to install

### ISSUE THREAD

**Issue by agrytnes** [vlasenko/zenbook-touchpad-i2c#1]
Hello,

First of all i want to thank you for fixing this problem.

I tried to install the the code put got some errors.

Im getting a "node-gyp rebuild" error.

I have the latest version of node.js and npm installed.

Thank you!
Andreas

[npm-debug.txt](https://github.com/vlasenko/zenbook-touchpad-i2c/files/590551/npm-debug.txt)

**Comment by kah0922** [comment]
I have the same issue on openSUSE Tumbleweed.
[npm-debug.txt](https://github.com/vlasenko/zenbook-touchpad-i2c/files/590852/npm-debug.txt)

**Comment by larixer** [comment]
i2c-bus build is failing. Unfortunately there is no information about the cause of i2c-bus install failing in attached npm-debug.txt. Please attach the full output from terminal instead, it does contains diagnostics about the error!

Please also check the page of `i2c-bus` project:
https://github.com/fivdi/i2c-bus

> If you're using Node.js v4 or higher and seeing lots of compile errors when installing i2c-bus, it's very likely that gcc/g++ 4.8 or higher are not installed.

**Comment by agrytnes** [comment]
Iv tried installing latest version of gcc/g++ and same problem occures.

![screenshot from 2016-11-15 07-55-54](https://cloud.githubusercontent.com/assets/23460540/20296196/b6f2fb40-ab09-11e6-9ee5-08194f20b38a.png)

**Comment by larixer** [comment]
Seems like it's a problem with your Node.js installation:
https://github.com/n-riesco/ijavascript/issues/35
You might want to try workaround listed there.

I never use system versions of Node.js, because they are often broken and outdated. Yours Node.js is v4.x which is outdated too as of now. The better way to install node is using NVM:
https://github.com/creationix/nvm

**Comment by agrytnes** [comment]
Ok! So now i have deleted node.js and nvm. After installation according to the link you posted I was able to get further. screenshot is from terminal after npm i. But i dont get any multitouch. npm start shows touchpads signals i terminal.
![screenshot from 2016-11-15 21-05-03](https://cloud.githubusercontent.com/assets/23460540/20323280/5353f8dc-ab7c-11e6-88cb-846d44538060.png)

**Comment by larixer** [comment]
Yes, thats what this project is about. It is about finding Magic packet to switch TouchPad into MutliTouch mode and start receiving MultiTouch signal. It is not a driver. But at this stage we have a userspace MultiTouch driver, the code is located here:
https://github.com/redmcg/FTE1001
